New branch
camfilho/youtube_clone pull request #10
Opened 2019-09-17 19:17 UTC by camfilho

2019-09-17 23:04 UTC, Forison requested changes
Hi @Lucasdfg and @Carlos 
# I would have loved to make you proceed to the next project but unfortunately, I can not until you rectify a few issues with your project.😇😇😇

- #### **[REQUIERED]**  HTML VALIDATOR ISSUES
First, I would like you to fix the errors given to you by the[ validator ](https://validator.w3.org)when uploading the index file.🙂

- #### **[REQUIERED]** README 
Your readme file is supposed to be descriptive enough(readme has to describe the project you have worked on in detail so that anyone who takes your project will have a fair view of what the project is about when they view the readme) It can involve link to live view of the project, Technologies used,contributors or even how to deploy your app etc....
NOTE > It all depends on your creativity.🙂 🙂 🙂 

- #### **[Required]** SEARCH BOX
search box looks goods but the button is detached from the search box (please improve upon it )

- #### **[Required]** NAV ICONS ON THE RIGHT
The navigation icons on the right are not looking good (please improve upon it)

- #### **[Required]** ASIDE ISSUE
The aside container is messy as it stands nows due to the margin-left given percentage. It would be ideal in this case to use "PX"

Note > % is good but it used can be tricky. Know when to use them to avoid messing up your code.

2019-09-17 23:24 UTC, Forison commented on style.css
> +.aladito {
This can be specified in pixel or reduced in its current unit, to avoid the mess it is causing now

2019-09-17 23:27 UTC, Forison commented on style.css
> +.divish {
This can be specified in pixel or reduced in its current unit, to avoid the mess it is causing now

2019-09-17 23:29 UTC, Forison requested changes
Guys, please fix the errors I have pointed out and submit your project for another review
t

## Do the stated corrections and submit code for review. 

feel free to contact me on LinkedIn, Twitter or slack for further clarification if necessary. I would be happy to assist you.
💪💪💪happy coding 💪💪💪

2019-09-18 00:09 UTC, camfilho commented
Hello @Forison ,
We didn't know where to look for the code review.
We are going to review it properly

2019-09-18 23:48 UTC, Redvanisation requested changes
*

2019-09-19 00:09 UTC, uche-inyama requested changes
## Pull requested under review by: Inyama, Uchechukwu Henry

2019-09-19 00:26 UTC, uche-inyama requested changes
## Hi team, :wave: you have some progress.
### You have corrected the html validation errors, as suggested by @Forison, although you missed one. :smiley: 
### However, your clone doesn't look like a youtube website.

Kindly go through this [link](https://github.com/camfilho/youtube_clone/pull/2#pullrequestreview-289170859). Revise the first and second points, then read the last paragraph. It is the feedback from one of TSEs that reviewed your work. The second point explains why you made this comment. ``` Hello @Forison ,
We didn't know where to look for the code review.
We are going to review it properly ```
- [**suggestion**] Google **font awesome** and use it for icons.

- [ ] Kindly work on your clone to look like a youtube page, you can inspect the website with your developer tools for more insight. :nerd_face: 

- [ ] Also, make your commit messages more descriptive. It should state what changes you made in your project, for future reference.

### After implementing these changes, submit another form for code review

### This project is not approved. :stop_sign:

2019-09-19 16:39 UTC, camfilho commented
@uche-inyama Thanks for the code review.
We have made the changes in the layout.
About the html validation, they are just warning us: "Section lacks heading. Consider using h2-h6 elements to add identifying headings to all sections". However, since we are not using text inside it, it would not be a good idea to add those tags.

2019-09-20 01:26 UTC, Ispirett approved these changes
Good Job Folks, I see that you are working hard on this project. Congratz with sticking with it.
Don't worry as you continue you will grow and become proficient with CSS .

![image](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png). 

You can merge this project. Good luck with the next project. 

**you can add margin-left: 2 em to your subscribe button.**
**Note trying using more descriptive names for your feature branch name**
**Note please fix conflicts before merging**

2019-09-20 01:26 UTC, Ispirett commented on index.html
> -    <nav>
**Optional** not required, I suggest wrapping your HTML in a `main` tag and then giving it a width of 90% and `margin: 0 auto`, This will center your code and give it some breathing room on the left.

2019-09-20 01:43 UTC, cerfectus commented on index.html
> -    <nav>
thanks for the comments man, really apreciate it, i will make the changes

2019-09-20 16:21 UTC, merged